name: Terraform

on:
  push:
    branches-ignore: [main, develop]
    # branches: [feature/*]
    paths:
      - 'terraform/**'
  pull_request:
    branches: [main, develop]
    paths:
      - 'terraform/**'

permissions:
  contents: read
  id-token: write

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terraform/gcp

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # - name: Authenticate to Google Cloud
      #   uses: google-github-actions/auth@v2
      #   with:
      #     credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

      - id: auth
        name: Authenticate to Google Cloud using Workload Identity Federation
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: 'projects/562177972330/locations/global/workloadIdentityPools/github-actions/providers/github'
          service_account: 'github-actions@project-2cf05b93-137c-46fd-bd7.iam.gserviceaccount.com'

      - name: Debug OIDC Claims
        uses: github/actions-oidc-debugger@main
        with:
          audience: 'https://iam.googleapis.com/projects/562177972330/locations/global/workloadIdentityPools/github-actions/providers/github'

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -input=false
